### ISSUE TITLE
ListCommand issues

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#101]
My app uses a style mechanism similar to the one in Pages. To this end it maintains model data describing the style structure of each document. This data is used to generate the attributed text whenever necessary. The issue I have faced is that Proton keeps the nesting structure of lists close to its chest, so it is impossible to regenerate it from model data. I have resolved this for now by saving a copy of the attributed text for each list and replacing it when the document is reloaded/updated. This is not ideal, but does work.

The other issue that I have yet to resolve is how to detect (a) double returns terminating a list and (b) backspacing into a list. It would be great if events could be signalled/state maintained so that these changes can be identified. Maybe this is already possible and I just haven't found it.

**Comment by rajdeep** [comment]
@writing-shed, have you tried using [ListParser](https://rajdeep.github.io/proton/Structs/ListParser.html) for the first issue you have described? I believe, it should help you in saving/restoring data to/from the Editor.

For the second issue, there's no clear callbacks that you can hook on to right now. I do agree that it could be helpful. Within the Lists processing code, I can add constructs that are able to relay this information. I'll try to get that in soon. Thanks for the suggestion.

**Comment by writing-shed** [comment]
Thanks, ListParser looks good. Unfortunately it doesn’t exist in v0.5.0!

I look forward to the callbacks.

**Comment by writing-shed** [comment]
I've abandoned my initial approach (part of my pre-Proton design) in favour of a new approach that accommodates the Proton design
