### ISSUE TITLE
"_blockContentType" doesn't conform to NSSecureCoding

### ISSUE THREAD

**Issue by santi-g-s** [rajdeep/proton#109]
Hi, sorry for bombarding you with issues recently. 

I am trying to save the attributedString created by Proton to Core Data. To save the `NSAttributedString` to core data I'm converting it to `NSData` using an `NSSecureUnarchiveFromDataTransformer`. This requires that everything conform to `NSSecureCoding` before being transformed into `NSData`. Here lies the problem

I believe the custom `NSAttributedString.Key`  - in my case "_blockContentType" came up a lot - don't conform to `NSSecureCoding` hence not allowing the `NSAttributedString`  to be stored to core data. Would it be possible to make it conform in some way?

**Comment by YoX89** [comment]
There are no guarantees in general that any attributes in `NSAttributedString` conform to `NSSecureCoding`. I think I've seen cases where attributes added by Apple don't conform. 

I had the same issue as you and what I ended up doing was to convert to a custom class myself and then store that in core data. Then when I need to edit it later I convert it back to `NSAttributedString`.

Maybe not the answer you are looking for but I hope it helps!

**Comment by santi-g-s** [comment]
@YoX89 Many thanks. I'll look into that. 

Forgive my lack of knowledge, but how would one go about converting NSAttributedString to a custom class?

Thanks again.

**Comment by rajdeep** [comment]
that's a great suggestion, @YoX89. @santi-g-s, a typical implementation that I have in mind when one would like to persist the text is by converting into a different kind of format. You can use your custom encoder/decoder for that. If you would like to see a custom implementation, you may refer to [custom encoders](https://github.com/rajdeep/proton/tree/master/ExampleApp/ExampleApp/Encoding/Encoders) that are there as an example in the Example App.  This approach will allow you to extend your code to accomodate whatever type you have. Proton is designed to be extensible and that is why I have added lots of extension points. Using these extensions, you and others should be able to use Proton in ways that even I have not thought of yet.
