### ISSUE TITLE
V0.6.0 won't compile with Xcode 12.5

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#113]
Just upgraded Xcode and Proton's ObjC code has stopped compiling - NS_ASSUME_NONNULL_BEGIN unknown.

I've tried going back to v0.5.0 but that won't compile because ListParser is not implemented in that version. So I'm stuck, although I could copy the ListParser code as a workaround.

**Comment by writing-shed** [comment]
Tried copying ListParser, but that won't compile because (I'm guessing) it depends on stuff in v0.6.0, so I am really stuffed.

**Comment by rajdeep** [comment]
thanks for reporting the issue, @writing-shed. I have fixed the issue and published a new release. Please try [v0.6.1](https://github.com/rajdeep/proton/releases/tag/v0.6.1).
