### ISSUE TITLE
Support Multiple `EditorListFormattingProvider`s in an editor

### ISSUE THREAD

**Issue by roanutil** [rajdeep/proton#115]
I'm looking into how to support multiple list formats in the same editor. At minimum it feels natural to support ordered and unordered lists in one editor. Before going too far, is this something already in progress? Would it be a welcome addition?

**Comment by rajdeep** [comment]
@roanutil, Proton already supports combining different types of list formats. ExampleApp includes a sample that shows how to combine multiple list formats. You may checkout the sample implementation [here](https://github.com/rajdeep/proton/blob/master/ExampleApp/ExampleApp/AdvancedFeatures/CommandsExampleViewController.swift#L248). Basic idea is that you need to add your custom [sequence generators](https://rajdeep.github.io/proton/Protocols/SequenceGenerator.html) which can then be used in [EditorListFormattingProvider.listLineMarkerFor(::::)](https://rajdeep.github.io/proton/Protocols/EditorListFormattingProvider.html#/s:6Proton28EditorListFormattingProviderP17listLineMarkerFor6editor5index5level13previousLevel14attributeValueAA0cgH0OAA0B4ViewC_S3iypSgtF) to generate desired type of list marker (ordered/unordered).

This is how it looks in action:
![lists-format](https://user-images.githubusercontent.com/266423/116803344-ee193300-ab59-11eb-9908-9134f41c2519.gif)

Hope this helps.

**Comment by roanutil** [comment]
To clarify what I mean:

Supporting multiple, independent list styles without changing indentation within the same list. To me, that's really one list style as it's just changing symbols for different indent levels.

Currently, I can't add a command for both ordered and unordered lists in the same editor.

**Comment by rajdeep** [comment]
@roanutil, this is something that can be done by the consumer i.e. like yourself. If you look at the signature of the function:
```swift
func listLineMarkerFor(editor: EditorView, index: Int, level: Int, previousLevel: Int, attributeValue: Any?) -> ListLineMarker
```
you can apply any custom value as an attribute to the list item text which will be passed into this function when the list is being laid out. Based on the attribute value, you can decide to return a numeric value or a bullet symbol. Other parameters like `level` and `previousLevel` may also be used to conditionally change the type of value being returned. 

Does this help?

**Comment by rajdeep** [comment]
@roanutil, I assume that you are able to get the lists working per your requirements. Please feel free to reopen this issue should you have any further questions.
