### ISSUE TITLE
Xcode 13

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#117]
Proton fails to compile with Xcode 13.0 beta. Error: CompileSwiftSources failed with nonzero exit code

**Comment by rajdeep** [comment]
thanks for reporting, @writing-shed. I'll check it out soon.

**Comment by rajdeep** [comment]
@writing-shed, I have verified Proton on Xcode Beta 13 (Big Sur) and it all seem to work fine. Can you see if there's an issue at your end?

<img width="1418" alt="compilation" src="https://user-images.githubusercontent.com/266423/121793829-30985a00-cc46-11eb-88bd-6fbc19831193.png">


https://user-images.githubusercontent.com/266423/121793833-3857fe80-cc46-11eb-987d-7bcbcae82a8d.mp4

**Comment by writing-shed** [comment]
I just tried it again and it worked. I use another package (SwiftUIX) that was failing. This is been corrected so perhaps there was some interaction. Who knows. I tried to change the proton version in the Example app but it failed adding a new package. It did the same on my app. Here is a screenshot:

<img width="507" alt="Screenshot 2021-06-13 at 07 32 28" src="https://user-images.githubusercontent.com/25199371/121797793-6d4e5c00-cc1a-11eb-9a9d-8325988a12d7.png">

**Comment by rajdeep** [comment]
@writing-shed, that's odd. I tried that too in the ExampleApp as well as a new app that I created to add the package. I am able to add that to both without any issues. I recommend doing a full clean using cmd-shift-K or clear your DerivedData folder.
<img width="777" alt="Screen Shot 2021-06-13 at 6 26 44 pm" src="https://user-images.githubusercontent.com/266423/121800459-5d179a80-cc75-11eb-8011-4457d8402288.png">

**Comment by writing-shed** [comment]
No, it definitely doesn't work for me. Are you using Xcode 13 beta? The package handling has changed - it now talks about package collections which were introduced with the new version. 

https://user-images.githubusercontent.com/25199371/121815234-41a89180-cc6d-11eb-9bb5-21de8ea93ba2.mov

**Comment by writing-shed** [comment]
Doh! They've changed the interface - entering the git url in the search field does the trick!
