### ISSUE TITLE
Range exception on deleting panel attachment from the inside

### ISSUE THREAD

**Issue by vox-humana** [rajdeep/proton#118]
Steps:
- Open ExampleApp
- Insert panel
- Remove empty line after the inserted panel
- Put cursor back inside the panel
- Press backspace once to delete the panel
- Press backspace second time to trigger the crash

I suspect that before calling `deleteBackward` in [parent RichTextView](https://github.com/rajdeep/proton/blob/master/Proton/Sources/Swift/Core/RichTextView.swift#L354) `selectedRange` hasn't been update and instead of empty range from `0` position contains empty range from `1` position. Not sure what's the right way to update this property 🤔

**Comment by rajdeep** [comment]
@vox-humana, thanks for reporting the issue.

**Comment by vox-humana** [comment]
Thanks for fixing it. For sure I would be looking into the wrong place trying to fix it 😅
