### ISSUE TITLE
How to run the ExampleApp?

### ISSUE THREAD

**Issue by MountainAndMorning** [rajdeep/proton#119]
How to run the ExampleApp?

**Comment by rajdeep** [comment]
hi @MountainAndMorning, you only need to select the "ExampleApp" scheme in the Xcode along with iPhone simulator/Mac that you wish to run this with.

<img width="522" alt="xcode" src="https://user-images.githubusercontent.com/266423/125557028-993ada06-1253-46f4-8729-b24ebaf2e83a.png">

Feel free to open this issue again in case you're running into some issues with a specific version of Xcode/device.
