### ISSUE TITLE
Problem with Strikethrough when changing attributedText

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#120]
Setting attributedText containing an attribute containing strikethrough results in strikethrough applied to all attributes. Setting the text with  an attribute containing underline results in strikethrough=0 appearing in the other attributes. Maybe the fact that both underline and strikethrough attributes use the same value type - namely NSUnderlineStyle.single.rawvalue?

Here are dumps taken from the setter at line 381 of EditorView.attributed text.

First the underline:

(lldb) po newValue
This {
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"title1\"), id: Optional(\"401D4EBD-B20F-4DE8-8A7F-A32A77F73CB4\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb4fd6f4e0> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 28.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
}test{
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"underline\"), id: Optional(\"16C65DC4-94FB-4851-96BE-8FE4FF04EC72\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb4fd6f4e0> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 28.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSUnderline = 1;
}

(lldb) po richTextView.attributedText
▿ Optional<NSAttributedString>
  - some : This {
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"largeTitle\"), id: Optional(\"FCDB90A0-557E-42D9-B64A-E18F702DC66A\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb3fc3f710> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 34.00pt";
    NSParagraphStyle = "Alignment 1, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSStrikethrough = 0;
}test{
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"underline\"), id: Optional(\"16C65DC4-94FB-4851-96BE-8FE4FF04EC72\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb3fc3f710> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 34.00pt";
    NSParagraphStyle = "Alignment 1, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSUnderline = 1;
}

Now the strikethrough case:

(lldb) po newValue
This {
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"title1\"), id: Optional(\"401D4EBD-B20F-4DE8-8A7F-A32A77F73CB4\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb4fd6f4e0> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 28.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
}test{
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"strikethrough\"), id: Optional(\"3B68996A-E9E7-497D-B20C-B4A1DA843DE3\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb4fd6f4e0> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 28.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSStrikethrough = 1;
}

(lldb) po richTextView.attributedText
▿ Optional<NSAttributedString>
  - some : This {
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"title1\"), id: Optional(\"401D4EBD-B20F-4DE8-8A7F-A32A77F73CB4\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb4fd6f4e0> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 28.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSStrikethrough = 1;
}test{
    EasiStyle = "Easiwriter.StyleIdentifier(name: Optional(\"strikethrough\"), id: Optional(\"3B68996A-E9E7-497D-B20C-B4A1DA843DE3\"))";
    NSColor = "<UIDynamicSystemColor: 0x600001eb57c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fbb4fd6f4e0> font-family: \"Helvetica Neue\"; font-weight: bold; font-style: normal; font-size: 28.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 10, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSStrikethrough = 1;
}

**Comment by rajdeep** [comment]
@writing-shed,
It looks like there might be an issue in how the attributes are getting applied in your code. Strikethrough and Underline have different attribute keys so it should not have ant effect on a range that these are applied to. Having same value does not have any side-effects.

To validate the same, I have added a new [AttributesToggleCommand](Proton/Sources/Swift/EditorCommand/Commands/AttributesToggleCommand.swift) with implementations for [Underline](Proton/Sources/Swift/EditorCommand/Commands/UnderlineCommand.swift) and [Strikethrough](Proton/Sources/Swift/EditorCommand/Commands/StrikethroughCommand.swift) and did not see any issues:

https://user-images.githubusercontent.com/266423/126769424-12150eef-74f8-4ccf-a291-972dc3c27056.mp4

**Comment by writing-shed** [comment]
I'm not sure you have understood the problem. Both underline and strikethrough work fine when applied to a continuous piece of text as shown in the example app. The problem occurs if you try and apply them to text with a range of differing underline attributes as in the dumps I sent you.

Here is a screenshot after the strikethrough is applied to some text:

<img width="329" alt="Screenshot 2021-07-25 at 09 14 09" src="https://user-images.githubusercontent.com/25199371/126892463-f7657db3-341d-478b-948f-ed5b12241dc2.png">

And here is the result of changing the style of the paragraph to include bold:

<img width="329" alt="Screenshot 2021-07-25 at 09 14 32" src="https://user-images.githubusercontent.com/25199371/126892474-dc9e8746-7802-45aa-86dc-8a1d0717923a.png">

I have traced the problem to the objc function at line 80 in PRTextStorage.m.

Line 84 picks up the attributes covering the last range (the word test in my dump)  while line 85 picks up the first (the word this in the dump) .

Lines 85 - 95  mangle the attributes passed to it by merging the underline attribute from the last set of attributes across all ranges.

I don't understand the comment about diacriticals, but suspect there is a conflict of goals here.

**Comment by rajdeep** [comment]
@writing-shed, I might still be missing the issue here. Does the following video reflect the case you're talking about? If not, can you please record a video to show what you're trying to do?

https://user-images.githubusercontent.com/266423/126893078-b0be6dd5-71f4-4abb-9610-75613d9f1795.mp4

**Comment by writing-shed** [comment]
Thanks for the reply. The app has a custom attribute for styles - paragraph and emphasis. I apply an emphasis (strikethrough) then apply a different paragraph style. If you look at the dumps I sent you will see what I mean. 

Best
Keith

**Comment by rajdeep** [comment]
I did try doing exactly the same thing as you have mentioned in your last comment, and I still do not see any issues:

https://user-images.githubusercontent.com/266423/126894698-62fca437-f284-4210-ab9b-6a89c60675de.mp4

Are you able to recreate the same issue in the ExampleApp so that I can debug the problem? 

There can be a number of reasons for the behaviour you're seeing in your code including the possibly incorrect range to apply attribute, changing an attribute which might otherwise be copied (i.e create a mutable copy) before changing. This is particularly required when you're changing specific aspects/properties of paragraphStyle.

**Comment by writing-shed** [comment]
The two lines I mention have the effect of splitting the attributedString provided to thee attributedText method then tue following code recombines it thereby propagating the underline attribute across tue the hole paragraph. I don't understand why this is done because it corrupts the input which is fine. I'll try and reproduce it in a test. 

Best
Keith

**Comment by writing-shed** [comment]
Hi

Here is a test that reproduces the issue. It happens if I call editor.attributedText twice. The first time with some stuck through text, the second with an attribute change to the paragraph	style (in fact probably any change). I’ve attached a test app for you to look at. It doesn’t matter if you don’t know SwiftUI -the issue is demonstrated in the two files TextViewTest and ProtoViewTest.

If you run the app you will see a window with two buttons. Click the 'Test UITextView’ button and you will see Hello World! With World! Struck through. Dismaiss the view by dragging down from the top. Then try the other button and you’ll see all the text struck through.

Best
Keith

**Comment by writing-shed** [comment]
[TestStrikethrough.zip](https://github.com/rajdeep/proton/files/6874087/TestStrikethrough.zip)

Here's the test

**Comment by writing-shed** [comment]
I've fixed this. I hadn't realised both underline attributes were needed whether true or false.

**Comment by writing-shed** [comment]
Hi

I haven’t been able to work on my app much lately, but am just getting back to it. Can you let me know if you are still working on Proton and, if so, when you expect to release v1.0.

Regards
Keith

**Comment by rajdeep** [comment]
@writing-shed, Proton is very much under active development. In fact, I've made 10 version bumps in last 3 months moving aggressively towards 1.0. I hope to get there sometime in first quarter of 2024. The library is pretty stable now and I don't expect too many breaking changes moving forward.
