### ISSUE TITLE
Build ExampleApp fails with Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_PREditorContentName"

### ISSUE THREAD

**Issue by 101airborne** [rajdeep/proton#127]
Trying to build  "proton-main.zip" or "proton-0.6.1.zip" ExampleApp fails with:

_Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PREditorContentName", referenced from:
      objc-class-ref in JSONDecoder.o
      objc-class-ref in JSONEncoder.o
      objc-class-ref in ParagraphEncoder.o
      objc-class-ref in WidthRangeAttachmentExampleViewController.o
      objc-class-ref in AutogrowingTextField.o
      objc-class-ref in PanelView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)_

Environment:  macOS 10.15.7, Xcode 12.4.

I note that there does not seem to be any build target for ProtonExtensions in the Proton.xcworkspace.

I could find no documentation on how one is supposed to integrate Proton into a project.  Shouldn't there be a documented Swift Package Manager URL?

**Comment by rajdeep** [comment]
@101airborne,
Thank you for reporting the issue. I'll check that out. In the mean time, you can use the following steps to add SPM dependency:

1. In your project in Xcode, select File-> Swift Packages -> Add Package Dependency.
2. Use the repo url: https://github.com/rajdeep/proton

<img width="719" alt="step1" src="https://user-images.githubusercontent.com/266423/135243574-c7955851-19e3-4cc4-acfb-9a9f3bc1df07.png">
<img width="719" alt="step2" src="https://user-images.githubusercontent.com/266423/135243587-0db9eaf5-00d4-448d-a234-28ac5230c04f.png">
<img width="719" alt="step3" src="https://user-images.githubusercontent.com/266423/135243595-05ff172a-fa22-4389-b839-71037510fd2d.png">

**Comment by 101airborne** [comment]
Thanks for info.  I was able to build my own sample project after adding SPM URL.  I then copied the ExampleApp folder from proton-main.zip and added the Proton SPM URL.  It wouldn't build until I deleted the Build Phase/Copy Frameworks and the Frameworks group. ExampleApp now builds and runs fine.

**Comment by rajdeep** [comment]
thank you, @101airborne. The issue has been fixed in the latest `main` branch.
