### ISSUE TITLE
Adding images to Proton.Attachment

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#136]
I am trying to add Images to EditView. I tried simply adding an NSTextAttachment containing an image which worked, but I couldn't find a way to detect touches. So...

I replicated the Panel and PanelView code in the ExampleApp as a way of adding Images. Again that works, but I still have the same problem - I can't detect touches. 

Have you tried this and made it work?

**Comment by rajdeep** [comment]
@writing-shed, since `Attachment` contains a `UIView`, you can add a `UITapGestureRecognizer` to the view in `Attachment` and have a `delegate` (if you need to handle that outside scope of attachment) that you can use from your app to get a callback when gesture recognizer is triggered.

**Comment by writing-shed** [comment]
Thanks. I've already tried that. Here's the code:

First the start of the PanelView
`class PanelView: UIView, BlockContent, EditorContentView {
    let container = UIView()
    let editor: EditorView
    let typeView = UILabel()
    weak var delegate: PanelViewDelegate?
    var tap: UITapGestureRecognizer?
`

Now the code to set up the recognizer:
`            tap = UITapGestureRecognizer(target: self, action: #selector(self.handleTap(_:)))
            container.addGestureRecognizer(tap!)
`

and the handler
`    @objc func handleTap(_ sender: UITapGestureRecognizer? = nil) {
        // handling code
`

I've traced through this and it gets setup as expected, but the handler is never called.

It should work, so I think the problem must be with SwiftUI. The EditorView is created in a UIViewRepresentable struct so methinks SwiftUI is stealing the events. I will check this out.

**Comment by writing-shed** [comment]
I realised that the container frame was zero so gave it the same dimensions as the image. This made no difference.

**Comment by rajdeep** [comment]
Try adding the view in attachment as a subview of the Editor directly. If you're able to invoke touch in this setup, it should work when in an attachment as well.

**Comment by writing-shed** [comment]
I tried your suggestion and it did respond to the touch, but didn't display the image. In the end, after a lot of experimenting, I abandoned the approach and tried using Attachment directly. So now I have the following Attachment class:

`class ImagePanel:Attachment {
    init<AttachmentView>(_ contentView: AttachmentView,
                                  size: AttachmentSize,
                                  editor:EditorView)
    where AttachmentView : UIView, AttachmentView : BlockContent {
        super.init(contentView, size: size)
        selectBeforeDelete = true
        editor.addSubview(contentView)
    }
}
`

The content is an ImageView defined as:

`class ImageView:UIImageView, BlockContent {
    var name: EditorContent.Name
    var tap:UITapGestureRecognizer?
    var isSelected:Bool = false

    override init(image: UIImage?) {
        name = .viewOnly()
        super.init(image: image)
        isUserInteractionEnabled = true
        tap = UITapGestureRecognizer(target: self, action: #selector(self.handleTap(_:)))
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    @objc func handleTap(_ sender: UITapGestureRecognizer? = nil) {
        // handling code
    }
}
`

The image is added by the following:

`    func addImage(data:Data?) {
        guard let data = data else {
            fatalError(ErrorDetails("No image to add"))
        }
        var image = UIImage(data: data)
        let width = editor!.bounds.width
        let scaleFactor = image!.size.width / width
        image = UIImage(data: data, scale: scaleFactor)
        let imageView = ImageView(image: image)
        let imagePanel = ImagePanel(imageView, size:.fullWidth, editor: editor!)
        editor!.insertAttachment(in: editor!.selectedRange, attachment: imagePanel)NSTextAttachmentView
    }
`
The image is inserted and displays OK, but the touch never gets activated with or without the contentView added as a subView of the editorView. I reckon this has to do with the comment at the end of the NSTextAttachment documentation where it talks about NSTextAttachmentViewProvider, but I haven't found any explanation how to use this.

**Comment by rajdeep** [comment]
I tried doing the same in ExampleApp and am able to get the tap working on the image. This is the code that I used:
```
class ImageAttachment: UIImageView, InlineContent {
    let name = EditorContent.Name(rawValue: "ImageContentView")

    var gestureRecognizer: UITapGestureRecognizer!
    override init(frame: CGRect) {
        super.init(frame: frame)
        gestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didTap(recognizer:)))
        self.image = UIImage(systemName: "car")
        isUserInteractionEnabled = true
        self.addGestureRecognizer(gestureRecognizer)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    @objc func didTap(recognizer: UITapGestureRecognizer) {
        if self.image == UIImage(systemName: "car") {
            self.image = UIImage(systemName: "car.2")
        } else {
            self.image = UIImage(systemName: "car")
        }
    }
}
```
and I add it to editor as follows:
```
let attachment = Attachment(ImageAttachment(frame: CGRect(origin: .zero, size: CGSize(width: 40, height: 40))), size: .fixed(width: width))
editor.insertAttachment(in: editor.selectedRange, attachment: attachment)
```

The image changes from one to another on tap:

https://user-images.githubusercontent.com/266423/152633151-0f46d0ff-3d73-4296-b260-b240a65eefe4.mov


**Are you missing** `self.addGestureRecognizer(gestureRecognizer)` on the attachment view itself?

**Comment by writing-shed** [comment]
Wow, at last! Thank you so much. I've got it working using a version of your code. I had misunderstood UIImageView so ended up with it drawing nothing when I tapped. Usual problem: RTFM.

It might be worthwhile enhancing Proton to support embedded images.
