### ISSUE TITLE
NSAttributedString error 

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#137]
When I save text containing an Proton.Attachment attribute it fails with this coding error:

`    NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=4866 \"The data couldn\U2019t be written because it isn\U2019t in the correct format.\" UserInfo={NSUnderlyingError=0x60000299d8f0 {Error Domain=NSCocoaErrorDomain Code=4864 \"This decoder will only decode classes that adopt NSSecureCoding. Class 'PREditorContentName' does not adopt it.\" UserInfo={NSDebugDescription=This decoder will only decode classes that adopt NSSecureCoding. Class 'PREditorContentName' does not adopt it.}}}";
`
The attributed string is:

`Optional<NSAttributedString>
  - some : ￼{
    NSAttachment = "<Proton.Attachment: 0x600003d7a340>";
    NSColor = "<UIDynamicSystemColor: 0x600001d207c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fb8e2209c30> font-family: \"UICTFontTextStyleBody\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
    NSParagraphStyle = "Alignment 4, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint ''";
    "_inlineContentType" = "EditorContent.Name(rawValue: \"BlockContentView\")";
    "_isBlockAttachment" = 0;
    "_isInlineAttachment" = 1;
} {
    NSColor = "<UIDynamicSystemColor: 0x600001d207c0; name = labelColor>";
    NSFont = "<UICTFont: 0x7fb8e2209c30> font-family: \"UICTFontTextStyleBody\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
    NSParagraphStyle = "Alignment 4, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint ''";
}
`

The core data attribute type is Transformable with a custom transformer. Storing the location of the Proton.Attachment isn't going to work anyway because there is no way to recreate it when it is reloaded (is there?).

**Comment by writing-shed** [comment]
Thinking about this I can see that I can’t save the editor attributed string with the images, but will have to save the images seperately and load them into the editor when the file is opened.

**Comment by rajdeep** [comment]
handled as part of #139
