### ISSUE TITLE
Crash in LayoutManager while updating Editor

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#138]
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[Proton.LayoutManager _fillLayoutHoleForCharacterRange:desiredNumberOfLines:isSoft:] *** attempted layout while textStorage is editing.  It is not valid to cause the layoutManager to do layout while the textStorage is editing (ie the textStorage has been sent a beginEditing message without a matching endEditing.)'
`

This happens while executing the following at line 108 during a call of replaceCharactersInRange in PRTextStorage.m

    for (NSTextAttachment *attachment in attachmentsToDelete) {
        [_textStorageDelegate textStorage:self didDelete:attachment];
    }

**Comment by rajdeep** [comment]
@writing-shed, do you have steps to recreate this issue? This may be caused by what happened before deleting the attachment during the same instance/flow.

**Comment by writing-shed** [comment]
I'd previously call insertAttachment thinking it would replace an existing one at the same location. Removing it sorted the issue, so thanks for the hint.
