### ISSUE TITLE
SecureCoding issue

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#139]
Im getting the following error when saving:

`CoreData: error: SQLCore dispatchRequest: exception handling request: <NSSQLSaveChangesRequestContext: 0x6000003e43c0> , <shared NSSecureUnarchiveFromData transformer> threw while encoding a value. with userInfo of {
    NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=4866 \"The data couldn\U2019t be written because it isn\U2019t in the correct format.\" UserInfo={NSUnderlyingError=0x60000383c9c0 {Error Domain=NSCocoaErrorDomain Code=4864 \"This decoder will only decode classes that adopt NSSecureCoding. Class 'PREditorContentName' does not adopt it.\" UserInfo={NSDebugDescription=This decoder will only decode classes that adopt NSSecureCoding. Class 'PREditorContentName' does not adopt it.}}}";
}`

One of the attributes is Transformable containing an NSAttributedString, which contains the offending attribute.

**Comment by rajdeep** [comment]
@writing-shed, I have made `EditorContentName` [compliant](https://github.com/rajdeep/proton/commit/787f955a9994c84867e0f2a46b4cd756cc8dd744) with `NSCoding`. You should be able to add an extension now to make it comply with NSSecureCoding:

```swift
extension EditorContentName: NSSecureCoding {
    public static var supportsSecureCoding: Bool {
        return true
    }
}
```

**Comment by writing-shed** [comment]
The extension doesn't compile - says EditorContentName can't be found. Maybe this is because it's obj-c code?

**Comment by vox-humana** [comment]
This is how the class looks like in Swift
<img width="521" alt="image" src="https://user-images.githubusercontent.com/53595/162592449-0a6c5892-4d57-40cc-8223-ca8b03f03d69.png">
Thus, it should be available in client code under this name.
@writing-shed are you sure you didn't forget to add `import Proton`?

**Comment by rajdeep** [comment]
@writing-shed, `EditorContentName` is defined originally as `PREditorContentName` which is under module `ProtonCore`.  I assume the issue is with `import` or linking.

**Comment by writing-shed** [comment]
I was importing Proton. You have to import ProtonCore!

**Comment by writing-shed** [comment]
Spoke too soon. It now fails with:

`CoreData: error: SQLCore dispatchRequest: exception handling request: <NSSQLSaveChangesRequestContext: 0x600000652ac0> , <shared NSSecureUnarchiveFromData transformer> threw while encoding a value. with userInfo of {
    NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=4866 \"The data couldn\U2019t be written because it isn\U2019t in the correct format.\" UserInfo={NSUnderlyingError=0x600003c4a190 {Error Domain=NSCocoaErrorDomain Code=4864 \"Class 'Proton.Attachment' has a superclass that supports secure coding, but 'Proton.Attachment' overrides -initWithCoder: and does not override +supportsSecureCoding. The class must implement +supportsSecureCoding and return YES to verify that its implementation of -initWithCoder: is secure coding compliant.\" UserInfo={NSDebugDescription=Class 'Proton.Attachment' has a superclass that supports secure coding, but 'Proton.Attachment' overrides -initWithCoder: and does not override +supportsSecureCoding. The class must implement +supportsSecureCoding and return YES to verify that its implementation of -initWithCoder: is secure coding compliant.}}}";
}
`

**Comment by rajdeep** [comment]
Does adding an extension not work for this too?

**Comment by writing-shed** [comment]
Extension to what?

**Comment by vox-humana** [comment]
@writing-shed the same conformance to `NSSecureCoding` in this `Proton.Attachment` class you are getting error about:
```
extension Attachment: NSSecureCoding {
    public static var supportsSecureCoding: Bool {
        return true
    }
}
```

**Comment by writing-shed** [comment]
I've now added:

```
extension EditorContentName: NSSecureCoding {
    public static var supportsSecureCoding: Bool {
        return true
    }
 }

extension Attachment {
    public static override var supportsSecureCoding: Bool {
        return true
    }
}

```

Which gives the error:

CoreData: error: SQLCore dispatchRequest: exception handling request: <NSSQLSaveChangesRequestContext: 0x600000486c40> , <shared NSSecureUnarchiveFromData transformer> threw while encoding a value. with userInfo of {
    NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=4866 \"The data couldn\U2019t be written because it isn\U2019t in the correct format.\" UserInfo={NSUnderlyingError=0x600003edd860 {Error Domain=NSCocoaErrorDomain Code=4864 \"This decoder will only decode classes that adopt NSSecureCoding. Class '__SwiftValue' does not adopt it.\" UserInfo={NSDebugDescription=This decoder will only decode classes that adopt NSSecureCoding. Class '__SwiftValue' does not adopt it.}}}";
}

**Comment by writing-shed** [comment]
I have decided to convert the Transformable attribute into a JSON String. However, a couple of Proton string attribute keys are internal - isBlockAttachment and isInlineAttachment. Can they be made public like inlineContentType etc?

**Comment by rajdeep** [comment]
that's probably a better idea in terms of scalability and maintenance. The last error that you're getting is because of the fact that `Attachment` defines init as follows:
```swift
 @available(*, unavailable, message: "init(coder:) unavailable, use init")
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```
This limits the decoding and implementing this may still not work depending of the views being used.

Coming back to your query on making `isBlockAttachment` and `isInlineAttachment` public: my recommendation would be to inspect the type of `view` to be `BlockContent` or `InlineContent`. This information would already be available to you and is the same logic used in these computed properties.

**Comment by writing-shed** [comment]
Thanks. The mapping from attributes to JSON takes place when the CoreData attribute is updated. If it finds inLineContentType set it sets isBlockAttachment to 0 and isInlineAttachment to 1, and vice versa if it finds blockContentType is set. Is that OK?

**Comment by rajdeep** [comment]
That sounds correct.

**Comment by writing-shed** [comment]
Hit a problem converting the data to JSON. It needs Proton.Attachment to conform to Codable.

**Comment by rajdeep** [comment]
Did you consider using `EditorContentEncoding` and `AttachmentEncoding`? `EditorView` has a function `transformContents` that uses `EditorContentEncoding` to encode contents including attachments. "Command Example" in the Example App also contains a simple example of encoding and decoding attachments and attributedString to JSON. The idea with encoders/decoders is that you should be able to extend it to write new encoder/decoders based on the attachments/views that you have.

**Comment by writing-shed** [comment]
Wow, that was quick. Thanks. I hadn't looked far enough to discover those.

**Comment by rajdeep** [comment]
Basic idea is that `Attachment` is just a container. What you really need to encode is the view (and possibly type of `Attachment` i.e `block` or `inline`). I believe, even in your code that you have been working with now, you may still be able to bypass encoding/decoding `Attachment` and work directly with the `view` you have in the attachment.

**Comment by rajdeep** [comment]
@writing-shed please let me know if this issue may be closed?
