### ISSUE TITLE
Is it suitable for email (html) composer?

### ISSUE THREAD

**Issue by pie6k** [rajdeep/proton#140]
I'm wondering if proton lib would be suitable for creating email composer.

The tricky part is that if you reply to html email, you see it under your reply and can edit it 

Example from Spark email app:
![image](https://user-images.githubusercontent.com/7311462/163668565-1dd6a85e-903a-49e1-aac8-3a3365c63e9a.png)

Thus seem such editor needs to support editing html or parsing html to some editable form and then back to html.

Would proton require tons of workarounds and hacks to achieve that ?

**Comment by rajdeep** [comment]
Proton Editor is just a UITextView under the hood. This means that you can simply create NSAttributedString from html and set in the Editor. 

Following is how you may create NSAttributedString from html:

NSAttributedString(data: self, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: String.Encoding.utf8.rawValue], documentAttributes: nil)
