### ISSUE TITLE
Is it suitable for a notes app that supports Apple Pencil functionality like Apple notes?

### ISSUE THREAD

**Issue by bryan1anderson** [rajdeep/proton#141]
I'm looking to create an editor in my journal app and need to know if I can plan on adding in an attachment view that is purely for drawing

**Comment by rajdeep** [comment]
@bryan1anderson, you may add any view in an `Attachment` i.e. if you create a view that supports only drawing, there's no reason why it won't work within the editor. I might have missed if you're looking for something specific so please elaborate if you have further questions.
