### ISSUE TITLE
Remove trailing space for background color

### ISSUE THREAD

**Issue by royherma** [rajdeep/proton#142]
<img width="467" alt="Screen Shot 2022-05-02 at 8 22 14" src="https://user-images.githubusercontent.com/3466248/166232828-b35f2f44-94f3-4071-bdb9-d91dcf8cea96.png">

When adding a background style/color to the EditorView, there is some extra "trailing space" when adding a new line / where new lines exist.

How do I make it so the background just covers the text itself (and not the extra spaces)?

Thanks so much, and love this library!

**Comment by rajdeep** [comment]
Glad you're enjoying Proton 👍 

This was not supported until now. I have added support to be able to achieve what you're trying to in this [commit](https://github.com/rajdeep/proton/commit/3acb2bafeca5c6523dc6a46dbe1d2b262f9baf2a). Besides other parameters for defining `BackgroundStyle`, you can now also provide `widthMode` which can be `.matchLine` (default) or `.matchText`. If you provide `.matchText`, it will draw background only where text is present.

The result produced is as following:
![testBackgroundStyleWithWidthModeAsText 1](https://user-images.githubusercontent.com/266423/166433589-3d2ebfbb-f403-4def-bcd4-d361c31f230d.png)

**Comment by royherma** [comment]
@rajdeep commented on commit - still don't think its handling cases with new line as desired. What do you think? Am i doing something wrong?

**Comment by rajdeep** [comment]
that's a good catch - I have pushed a fix for that [here](https://github.com/rajdeep/proton/commit/c1867b185872e05062685700442ff6dd0d98c238). I also found another issue wherein the borders would not merge properly with some very specific layout of text. I'll be fixing that in coming days. It should ideally not affect your case.
