### ISSUE TITLE
Crash when sometimes escaping a list

### ISSUE THREAD

**Issue by bryan1anderson** [rajdeep/proton#147]
Thread 1: "*** -[NSBigMutableString _getBlockStart:end:contentsEnd:forRange:stopAtLineSeparators:]: Range {7, 0} out of bounds; string length 6"

Basically I just go in, create a list and then hit enter to reproduce

**Comment by rajdeep** [comment]
@bryan1anderson, can you please provide detailed steps or the data that you are putting in the list? I am not able to recreate it with what you have mentioned.

**Comment by ChristopherAdelmann** [comment]
I have similar Problems. A more detailed explanation:

- Create List
- Return (New line)
- Indent List
- Return (New line)
- Crash

It appears that in `textViewDidChange(_ textView:)` of `RichTextEditorContext` the `richTextView.selectedRange` is out of bounds and might cause the problems.
![Simulator Screen Shot - iPad (10th generation) - 2023-04-09 at 21 21 34](https://user-images.githubusercontent.com/34486683/230792510-a7db5bc6-ae43-46f2-b6c3-eaf584c9cb95.png)

**Comment by rajdeep** [comment]
thank you for providing the steps @ChristopherAdelmann. I was able to narrow down and fix the crash. Please try the latest `main`.
 

https://user-images.githubusercontent.com/266423/230874885-2077e187-b93d-40dd-b69c-b92f09c135bf.mp4
