### ISSUE TITLE
Make first line of text view a specific font

### ISSUE THREAD

**Issue by bryan1anderson** [rajdeep/proton#150]
I'm trying to do this. I found a solution that will seemingly work here: https://hartl.co/2015/05/21/Highlight-first-line.html

However, EditorViewDelegate does not pass through 
`textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool` so I'm having a hard time.

What do you recommend?

**Comment by rajdeep** [comment]
To apply any style in Editor, you need to add style using `NSAttributedString` attributes. In this case, you need to add attribute for `.font` with value using font that you wish to apply, for e.g. `UIFont.preferredFont(forTextStyle: .largeTitle)`. If you wish to apply the style when user taps a button, you can use a custom `EditorCommand` for that. However, if you wish to apply style as user types the content, you will need a `TextProcessor`. Please refer to examples in the `ExampleApp` for both these cases.

**Comment by bryan1anderson** [comment]
Its TextProcessor that I was missing sorry about that and thanks for such an incredible library!
