### ISSUE TITLE
func editor(_ editor: EditorView, didReceiveKey key: EditorKey, at range: NSRange) not called on Enter

### ISSUE THREAD

**Issue by bryan1anderson** [rajdeep/proton#151]
Haven't been able to get this work. I'm running iOS 16. Backspace seems to be the only key it registers

**Comment by rajdeep** [comment]
`Enter` key is only supported with modifiers like `Shift`. I have made change to relay `Enter` via delegate even without modifiers. Please try the latest [commit](https://github.com/rajdeep/proton/commit/751c0239be148b584e8ed14dcc4a6a57f642e90d).
