### ISSUE TITLE
Edit menu

### ISSUE THREAD

**Issue by easiwriter** [rajdeep/proton#157]
Is there any way to suppress or change the display of the edit popup menu to a long tap gesture?

**Comment by rajdeep** [comment]
@easiwriter, you can subclass `EditorView` and overrider [canPerformMenuAction](https://rajdeep.github.io/proton/Classes/EditorView.html#/s:6Proton10EditorViewC20canPerformMenuAction_10withSenderSb10ObjectiveC8SelectorV_ypSgtF). Returning `false` will disable menu or you can selectively disable specific selectors. Showing Edit menu on long tap is not supported by default but depending on your requirements, you may be able to have a custom implementation similar to how you add log tap gesture to any other view.

**Comment by easiwriter** [comment]
Thanks for this. I have been away from my project for a few months and don’t remember the menu popping up when I tap on an editor view before, so was wondering if this is something you’ve added?

**Comment by rajdeep** [comment]
I hope issue that you were facing is resolved. Please feel free to reopen and provide further details, if it isn't.
