### ISSUE TITLE
No such module 'Proton'

### ISSUE THREAD

**Issue by mrjlovetian** [rajdeep/proton#158]
Hello, use SPM 0.6.1 Xcode No such module 'Proton'
![Uploading 截屏2023-01-05 18.13.40.png…]()

**Comment by Youngseo-Jeon0313** [comment]
try to paste the github address down here.
https://github.com/rajdeep/proton

**Comment by rajdeep** [comment]
@mrjlovetian, if you are still facing issues, please post details and reopen this issue.
