### ISSUE TITLE
Unexpected list indent when toggling list in new line that already has list item.

### ISSUE THREAD

**Issue by ChristopherAdelmann** [rajdeep/proton#165]
I encountered an unexpected list indentation instead of list removal after the following steps:

1. Toggle list
2. Return (New line)
3. Toggle list
4. Indentation instead of removal of the list item

I assume this is because of `ListCommand` line 85:
`guard selectedRange.length > 0 else {
            ListTextProcessor().createListItemInANewLine(editor: editor, editedRange: selectedRange, indentMode: .indent, attributeValue: attributeValue)
            return
        }`

A check on whether the current line already has a list item might be useful before creating a new list item.

Btw, congrats on this great package, very useful for complex text views.

https://user-images.githubusercontent.com/34486683/230959354-b83c111f-9421-4af4-9935-937a1c86d26b.mov

**Comment by rajdeep** [comment]
@ChristopherAdelmann, thank you for reporting the issue. I have fixed that in the latest `main`. Please give it a try.


https://user-images.githubusercontent.com/266423/231020646-84c56560-d8d2-475c-aa3d-587939b6c8f1.mp4
