### ISSUE TITLE
What document format supported?

### ISSUE THREAD

**Issue by zhouhao27** [rajdeep/proton#167]
I'm wondering what document format you're supporting. Do you support to save the document in html, docx or other format? Thanks.

**Comment by rajdeep** [comment]
By default, Proton only supports `NSAttributedString` for read and write operations and not any particular document format. However, it also provides certain helpers in form of Encoders and Decoders that can be used to convert attributedString to/from any other format including any custom format. Have a look at [EditorContentDecoding](https://rajdeep.github.io/proton/Protocols/EditorContentDecoding.html) and [EditorContentEncoding](https://rajdeep.github.io/proton/Protocols/EditorContentEncoding.html). There is also a simple usage example in ExampleApp demonstrating the same. You may choose to use these protocols to convert between attributedText and a document format that you wish to support or you can write your custom encoders/decoders.
