### ISSUE TITLE
EditorView's placeholder frame is incorrect when adjusting insets

### ISSUE THREAD

**Issue by pixelmatrix** [rajdeep/proton#168]
For my use case, I wanted the EditorView to not have any padding, so I've set `contentInset` and `textContainerInset` to `.zero` immediately after initialization. However, I noticed that this causes the placeholder label to be misaligned.

My code:

```swift
let textView = EditorView()
textView.contentInset = .zero
textView.textContainerInset = .zero
textView.placeholderText = NSAttributedString(string: "Write something…", attributes: placeholderAttributes)
        
// Trigger placeholder frame update
textView.attributedText = NSAttributedString(string: " ")
textView.attributedText = NSAttributedString(string: "")
```

It seems the placeholder label's constraints are evaluated only on initialization and when visibility is toggled after an edit is made.

On line 294 of RichTextView:

```swift
private func setupPlaceholder() {
        placeholderLabel.accessibilityIdentifier = "RichTextView.placeholderLabel"
        placeholderLabel.translatesAutoresizingMaskIntoConstraints = false
        placeholderLabel.numberOfLines = 0
        placeholderLabel.lineBreakMode = .byTruncatingTail

        addSubview(placeholderLabel)
        placeholderLabel.attributedText = placeholderText
        NSLayoutConstraint.activate([
            placeholderLabel.topAnchor.constraint(equalTo: self.topAnchor, constant: textContainerInset.top),
            placeholderLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -textContainerInset.bottom),
            placeholderLabel.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: textContainer.lineFragmentPadding),
            placeholderLabel.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: -textContainer.lineFragmentPadding),
            placeholderLabel.widthAnchor.constraint(equalTo: self.widthAnchor, constant: -textContainer.lineFragmentPadding)
        ])
    }
```

At initialization `textContainerInset` is 8 by default, and that offset remains cached until the constraints are recreated later.

As a workaround for now, I'm setting `attributedText` to a single space, and then setting it back to an empty string to trigger the update, but it would be nice if this worked out of the box.

I think a solution would be a call to `setupPlaceholder()` when the relevant insets change.

**Comment by rajdeep** [comment]
thank you for reporting the issue @pixelmatrix. I have fixed it in the latest `main`. Checkout the output [here](https://github.com/rajdeep/proton/blob/main/Proton/Tests/Editor/__Snapshots__/EditorSnapshotTests/testUpdatesPlaceholderWithInsets.1.png).

**Comment by pixelmatrix** [comment]
Amazing! Thanks for fixing this so quickly
