### ISSUE TITLE
Missing public init for ListItem

### ISSUE THREAD

**Issue by ChristopherAdelmann** [rajdeep/proton#170]
Currently, `ListItem` is not initializable due to internal protection of init.
Addition of public init is necessary in order to work in conjunction with `ListParser`.
See [Internal protection in frameworks](https://stackoverflow.com/questions/54673224/public-struct-in-framework-init-is-inaccessible-due-to-internal-protection-lev)

**Comment by rajdeep** [comment]
ah! that's an oversight on my part. [Fixed](https://github.com/rajdeep/proton/commit/d400a09acecb59a70b81a3bc366666b84f5bb4f0) in the latest `main`. Thank you for reporting the issue, @ChristopherAdelmann.
