### ISSUE TITLE
how can i selected text in some panel

### ISSUE THREAD

**Issue by dyljqq** [rajdeep/proton#175]
forexample, when i insert a lot of panel attachment in editorview, and every panel have an editor, how can i choose text from panel A to panel C, maybe i will choose part of text at panel A, so you can't select from the parent editor.

**Comment by rajdeep** [comment]
@dyljqq, partial selection of panels is not yet supported in Proton. You can select the content from main editor and entire panel though.

**Comment by dyljqq** [comment]
> @dyljqq, partial selection of panels is not yet supported in Proton. You can select the content from main editor and entire panel though.

i known, but my leader think, must can have select any text in the editor, so...now, i want to use list command in editor to achive the checklist, you known, but your method is to render the image in the header indent, so i cannot choose the checklist, and change its style. how can i do.

**Comment by rajdeep** [comment]
@dyljqq, for adding a checklist, you can add an attachment with checkbox and use paragraph style for indentation. Though checklist is not supported in Proton using ListCommand yet, I can look into a adding that support in near future.

**Comment by dyljqq** [comment]
> @dyljqq, for adding a checklist, you can add an attachment with checkbox and use paragraph style for indentation. Though checklist is not supported in Proton using ListCommand yet, I can look into a adding that support in near future.

i have complete the checklist as attachment, but my leader also think the checklist should selected text from checklist to the editor, which the checklist attachment is in this editor. 
i also used to render the checklist as a bullet, but i find it cannot touch the header indent area,:
```
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        if let touch = touches.first {
            let position = touch.location(in: self)
            didTap(at: position)
        }
    }
```
when i touch the checklist, it cannot be trigger. And i dont known why.

so i think, maybe i can insert the checklist as image in the attribute string, just like this:
```
textStorage.enumerateAttribute(.checklist, in: textStorage.fullRange) { value, range, _ in
            guard value != nil else { return }
            print("range: \(range)")
        }
```
in the drawGlyphs methods on LayoutManager

**Comment by rajdeep** [comment]
@dyljqq If you add checkbox as a view in attachment, you should be able to check it. In this case, layout manager does not come in picture. If you're doing anything with layout manager, you're likely rendering it as an image and not a view.

**Comment by dyljqq** [comment]
> @dyljqq If you add checkbox as a view in attachment, you should be able to check it. In this case, layout manager does not come in picture. If you're doing anything with layout manager, you're likely rendering it as an image and not a view.

do you known how apple's notes app checklist to complete? its not like the checklist image insert in attributestring, how its change is the nsattachment change?

**Comment by dyljqq** [comment]
Thx, i have solve my problem.
I render the check box view as your bullet & number render way.
And change the attribute value, if i check / uncheck the box.
