### ISSUE TITLE
[bug] Space rendered wider after emoji

### ISSUE THREAD

**Issue by kangzhang** [rajdeep/proton#197]
Hey there, we recently ran into this bug with space character rendering, wonder if you could take a look:

To repro:

* Add an emoji '🤣'
* Add a <space> character, notice the space is larger than a normal space

Expected behavior
* The <space> after emoji is the same size as a normal <space>

Here is a video cast showing the bug

https://github.com/rajdeep/proton/assets/38459/8becdb17-2a50-492c-b7d8-21ab094bafc8

Also thanks for this awesome library, we have been using it in our app and it saved us a lot of time!

**Comment by rajdeep** [comment]
@kangzhang, this seems really odd as I have never experienced such behaviour. I have verified again in Proton Example app and it seems to be working as expected. Please see attached below.

To debug this issue and get more details, I recommend looking at the following:
- Verify the attributed string in Editor after adding spaces. Do you see a space character or something else?
- Try pressing backspace to validate that it also deletes wide character. This will confirm whether it's a single character or multiple characters getting added.
- Are you using any TextProcessor that might be changing this behaviour?
- Try out ExampleApp in Proton. Do you experience the same behaviour?

https://github.com/rajdeep/proton/assets/266423/e0d3697c-12bb-4b62-aaf6-66f6a5ddc202

**Comment by kangzhang** [comment]
@rajdeep - thanks a lot for that quick & detailed response! I gave it more tries and it seems that some custom fonts might be causing the issue - the bug went away after I turn off the font and I don't see it reproing in your demo. 

I'll take a closer look at where the problem is. Thanks again!

**Comment by rajdeep** [comment]
Thank you, @kangzhang. I'll have a look and incorporate the change in the upcoming release.

**Comment by rajdeep** [comment]
merged in #215
