### ISSUE TITLE
Can't launch Example app, No such module 'Proton'

### ISSUE THREAD

**Issue by chernushevich** [rajdeep/proton#205]
Not sure what I'm missing here, but I can't seem to lauch the Example app, no matter what I try.

Xcode 15 Beta 4, Mac OS Ventura 13.4.1

![Screenshot 2023-07-27 at 00 58 54](https://github.com/rajdeep/proton/assets/1441165/46cdf1d6-36c4-4233-ae03-c0402ca42bf6)

**Comment by rajdeep** [comment]
@chernushevich, I have verified with Xcode 15 Beta 5, Ventura 13.4 and don't see any issues running the example app. I can only recommend verifying that you do not have any local changes, trying a clean build and if noting works, then may be checkout the project again.

<img width="458" alt="image" src="https://github.com/rajdeep/proton/assets/266423/aa1e9312-4dab-41d8-93af-eeb948e9a52c">

**Comment by brechtknecht** [comment]
Had the same problem with Xcode 15 (15A240d) and Sonoma 14.0.

I resolved this issue by adding proton as a package dependency and then by removing the red proton items from the `Frameworks` folder within the Xcode file explorer.

Note, I needed to manually set the target to `Example App` when adding the package dependency.
<img width="1114" alt="image" src="https://github.com/rajdeep/proton/assets/6838053/e347186d-9e6c-40d0-8dde-cecf3e8d2fb2">

**Comment by richard-dzavoronok** [comment]
I had same problem and then I realized the @rajdeep did a good job structuring this project.

You just have to open Proton.xcworkspace (not ExampleApp.xcodeproj), wait for build to finish, change target to ExampleApp and run it.
