### ISSUE TITLE
API for easily inserting a character at the given selection point, maintaining current style?

### ISSUE THREAD

**Issue by MilesV64** [rajdeep/proton#222]
Hello, thank you for this library! I'm wrapping my head around it for usage in a production app and so far it's looking great. One use case I have is when the user clicks a button, a small inline view gets inserted at the selection point. That's working great so far, but I want to actually surround that attachment with an empty space (" ") on both sides, and then move the cursor to after the trailing space. 

Does this library have an easy API for inserting characters, rather than just attachments? If not, what's the best way to go about inserting a character while matching style (font size etc)?

I don't want to add space in the attachment view itself because if it's the first thing on a line, I want it to perfectly match the left margin. 

I don't want this issue to get too unfocused but it would be great to have public access to the `RichTextView` even if its only casted as a generic `UIScrollView` -- this is important to me because I have some views which need to read from a scroll view's pan gesture recognizer for certain pull-to-dismiss gestures. Also so I can set `delaysContentTouches` to `false` as my attachment is a button and it feels nicer to have instant feedback :)

Thanks again!

Edit: Also, is there a way to get a delegate callback when anything in the text content changes, including inserting/deleting attachments? I only see `editor(_ editor: EditorView, didChangeTextAt range: NSRange)` for that use case which is only text changes.

**Comment by rajdeep** [comment]
@MilesV64, glad you're finding Proton helpful. For your case of inserting text at a given range, you should be able to use [replaceCharacters](https://rajdeep.github.io/proton/Classes/EditorView.html#/s:6Proton10EditorViewC17replaceCharacters2in4withySo8_NSRangeV_So18NSAttributedStringCtF). You can prepare your content i.e. attachment with required spaces on either side and use `replaceCharacters` to append that to the Editor at given range/selectedRange. `Attachment` also has a `string` property that you can use to get an `NSAttributedString` representation that you can use to append spaces easily. In regards to the attributes, you can look at `editor.typingAttributes` and add that to your prepared string. In summary:
* Create a mutable attributedString with space as starting character, if applicable.
* Append attachment.string
* Append trailing space
* Add typingAttributes from the editor to the entire string
* Use `replaceCharacters` to add the attachment/spaces to Editor.

In regards to `RichTextView`, it is not exposed as there are some constructs that are required for Proton to work which, if RichTextView is public, may get accidentally overriden by consumers causing unexpected results. Exposing some bits may still be possible but I think we need to discuss that as a separate issue.

For intercepting content changes, you may want to look at [TextProcessors](https://rajdeep.github.io/proton/Protocols/TextProcessing.html) that does provide content related callbacks including that for [insert/delete text](https://rajdeep.github.io/proton/Protocols/TextProcessing.html#/s:6Proton14TextProcessingP11willProcess07deletedB008insertedB0ySo18NSAttributedStringC_AHtF), which may also be an attachment

**Comment by MilesV64** [comment]
Thank you, I appreciate the response! This all sounds good.
