### ISSUE TITLE
Publicly expose the underlying UIScrollView

### ISSUE THREAD

**Issue by MilesV64** [rajdeep/proton#223]
It's often important to have access to a `UIScrollView` powering a view in order to update UI on scroll, get the current offset, and attach/intercept gesture recognizers (think a pull down animation that only pulls down when the scroll view is scrolled to the top, like dismissing an iOS modal view controller).

It would be great to have access to the scroll view powering the `EditorView` for those reasons. I understand not wanting the consumer to break the editor by directly modifying the scrollview, but somehow it would be really good to be able to at least:
- Receive UIScrollViewDelegate methods (either by directly being able to set the delegate, or adding them to `EditorViewDelegate`
- Access the `UIScrollView.panGestureRecognizer` as it's important for implementing the pull-to-dismiss modal behavior (UIKit does this automatically in a modal, but I need a custom implementation of modals)

**Comment by rajdeep** [comment]
@MilesV64, I'll put this in my backlog to look at. Hopefully, I'll get on this soon.

**Comment by rajdeep** [comment]
@MilesV64, requested changes have been made in the latest `main` (#226). Will be included in the upcoming release.
