### ISSUE TITLE
Add SPM support

### ISSUE THREAD

**Issue by rajdeep** [rajdeep/proton#26]

**Comment by vmanot** [comment]
@rajdeep any ETA on this? Happy to pitch in, if there are no major technical roadblocks to adding SPM support.

**Comment by rajdeep** [comment]
Hey @vmanot! I don't see any major issues other than the fact that I've not been able to manage time to get to it. Would be great if you'd like to contribute. 

Thanks!

**Comment by vmanot** [comment]
@rajdeep I'll try and open a PR soon.

**Comment by rajdeep** [comment]
Closed in #54

**Comment by Alexs7zzh** [comment]
Because of the added objective-c code, Proton cannot be added via SPM any more. Error message:

> target at '/Users/.../SourcePackages/checkouts/Proton/Sources' contains mixed language source files; feature not supported

**Comment by rajdeep** [comment]
@Alexs7zzh, can you please provide some more details about your project and environment? I did a quick test and I am able to import proton using SPM:

<img width="261" alt="test_proj" src="https://user-images.githubusercontent.com/266423/96674770-3f7b8500-13b5-11eb-8601-3b31100c1ae3.png">

Obj-C code was added to Proton owing to poor performance of Swift based NSTextStorage which is something that Apple needs to look at. To provide some context, have a look at the side by side comparison of ObjC vs Swift based NSTextStorage:
![text-storage](https://user-images.githubusercontent.com/266423/96675366-77cf9300-13b6-11eb-881c-3cdfe4c53fd6.gif)

**Comment by Alexs7zzh** [comment]
@rajdeep Thanks for the reply!
I initiated an empty project and tried importing Proton. I find out I will only encounter this error when I set the rule of SPM to `Branch: Master`. I succeeded when importing based on version number.

FYI: I am running Xcode 12.2 beta 3 (12B5035g) on macOS Big Sure 11.0 Beta (20A5395g). I also tried Xcode 12.0.1 (12A7300). They have the same results.

**Comment by rajdeep** [comment]
thanks for additional details, @Alexs7zzh. I have been testing on Catalina only as I do not have access to a machine with Big Sur yet. I'll look into it to see if I can find anything. It might end up being a bug on Apple's side - though, we need to investigate further to be able to conclude that.

**Comment by vmanot** [comment]
@rajdeep fixed in #82.

**Comment by rajdeep** [comment]
thank you, @vmanot. I will have a look at #82 - hopefully in  current week itself.

**Comment by vmanot** [comment]
@rajdeep sounds good! Let me know if you run into any issues. There's only one test failing currently, not sure what that's about.
