### ISSUE TITLE
Native visionOS support

### ISSUE THREAD

**Issue by bryan1anderson** [rajdeep/proton#266]
Hoping its not too heavy a lift considering this is backed by UITextView which is available in visionOS

**Comment by rajdeep** [comment]
@bryan1anderson, I haven't tried it out yet, but I would assume it should just work. Depending on your use case, you might have to use a SwiftUI wrapper though.

Happy to look into any issues that you might run into with Proton on VisionOS.

**Comment by bryan1anderson** [comment]
@rajdeep here is a PR for that change. https://github.com/rajdeep/proton/pull/267

**Comment by rajdeep** [comment]
Thanks @bryan1anderson, I'll take a look at it over the weekend.

**Comment by rajdeep** [comment]
merged as part of #272
