### ISSUE TITLE
Package fails to load

### ISSUE THREAD

**Issue by easiwriter** [rajdeep/proton#276]
Using Xcode 15.1 and 15.2 Proton fails to load (as do other packages). Loading works with the latest beta, but is a bit shaky. The eror I'm getting is 'package(name:url:_:) is deprecated: use specific requirement API's instead'.

**Comment by rajdeep** [comment]
@easiwriter,  I have not seen this issue and have been using Xcode 15.1. This SO question talks about the same thing: https://stackoverflow.com/questions/71484022/spm-dependencies-branch-is-deprecated-on-xcode-13-3-and-swift-5-6. Have you checked this out yet?
