### ISSUE TITLE
Xcode issue

### ISSUE THREAD

**Issue by easiwriter** [rajdeep/proton#308]
I've just upgraded to v15.4 and hit a problems compiling Proton related code. I'm getting the message:

Type 'AttributedTextView.Coordinator' cannot conform to protocol 'EditorViewDelegate' because it has requirements that cannot be satisfied. The Coordinator is a class required by UIViewRepresentatble.

I haven't changed my code so can't work out what this means. What requirements might it refer to?

I've also noticed that I've for v0.8.35 installed though this site says 0.8.33.1 is the latest?

**Comment by easiwriter** [comment]
Well, it just went away on the next compilation attempt!!

**Comment by rajdeep** [comment]
@easiwriter, would it be possible for you to provide a sample project showing this issue? That might help me look into it at the correct place. 

Also, 0.8.35 is the latest. 0.8.33.1 was a patch created on top of 0.8.33 which would not have all the changes from 0.8.34 and 0.8.35.

**Comment by easiwriter** [comment]
Thanks for the reply. The compilation problem went away again and hasn’t returned. However, the code suddenly started looping as soon as it tried to load an editor window. I’ve just spent a day tracking this down. It’s nothing to do with Proton, rather SwiftUI has apparently tightened up its rules for tracking view updates, the result in this case being that it keeps seeing my editor view as changed. I know what’s doing it and am rather fed up with Apple for making changes that affect code that’s worked for a couple of years. Not only that but the DisclosureGroup view also stopped working properly. Being a developer is hard enough without these (undocumented) changes to the undergrowth! 

(Rant over)

Cheers
Keith

**Comment by rajdeep** [comment]
@easiwriter, I hear you. There have always been these challenges and some do not even make sense but oh well, we can just hope things get better with time. 

I'm closing this issue. Please feel free to open this again should you find something that may still need to be looked at.
