### ISSUE TITLE
Shared UIMenuController

### ISSUE THREAD

**Issue by easiwriter** [rajdeep/proton#313]
Does Proton support the sharedMenuController? I want to add the edit popup to my app and have used this in another app. I know that UIMenuController is now deprecated in favour of UIEditMenuInteraction. If Proton doesn't support what would be the best way to implement it?

**Comment by easiwriter** [comment]
I have tried to implement this using UIEditMenuInteraction but failed because I can't get hold of the UITextView inside RichTextView as it's declared as internal. Any chance you could provide a getter for it?

**Comment by rajdeep** [comment]
@easiwriter, `RichTextView` cannot be exposed outside as it can cause a lot of unintended side-effects. However, I have updated the `EditorView` to  add support for adding interaction in #314 and has merged it in. I'll be creating a release in a few days as I need to fix certain things with the ongoing work with tables. You should still be able to point to the latest commit to use the new API.

**Comment by easiwriter** [comment]
Excellent. Many thanks.
