### ISSUE TITLE
ProtonExtensions.framework: Introduce a “Standard Library” of common plugins

### ISSUE THREAD

**Issue by rjchatfield** [rajdeep/proton#4]
This repo currently contains the core Editor as a framework and the example project. I believe there is space for a framework which contains text processors and commands for common editor behaviour.

- H1/2/3/4/5/6 
- Bold/Italics/Strike-through
- Bullet point
 
Implementing the Text Processor for markdown (* _ #) would be great. Additionally and separately we can co-develop a Command for allowing the Integrator to implement a key command or UIButton action. 

These ProtonExtensions are optional and can be ignored by the Integrator - but it is assumed that these will be valuable to most Editor usages. The Example app in this repo will use these extensions, as well as demoing some exotic examples not suitable for production.

**Comment by rajdeep** [comment]
As of now, ProtonExtension has been removed from being a separate project. If need arises, this will be recreated in future.
