### ISSUE TITLE
Cursor is bigger than font line height when editor has spacing

### ISSUE THREAD

**Issue by vox-humana** [rajdeep/proton#45]
When TextView has `paragraphSpacingBefore` or `paragraphSpacing` cursor covers this spaces and this seems not right especially when you have line selection.

Screenshots from Example app with these properties are set in `paragraphStyle`
<img width="135" alt="image" src="https://user-images.githubusercontent.com/53595/85084896-754b0a00-b219-11ea-80b5-31d7d72391f7.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/53595/85084850-5cdaef80-b219-11ea-9cc0-1a263b2d9762.png">
PR is coming...

**Comment by vox-humana** [comment]
There is one place left. After an attachment text cursor is as toll as this attachment height if it is at the very end position. 
Need to bring a special fix for this last character use case. Instead of using previous character line height, probably, need to get current line height from typing attributes.

**Comment by rajdeep** [comment]
Why not consider using typing attributes at all times to get the height of the text?
