### ISSUE TITLE
FontTraitToggleCommand overwrites last executed command.

### ISSUE THREAD

**Issue by YoX89** [rajdeep/proton#64]
Hi,

This bug can be reproduced using the example app using the "Commands" example.

1. Write any letter.
2. Select Bold and Italic.
3. Write any letter.

The letter will now only be italic.

The code in question is the following in FontTraitToggleCommand.
```
        if selectedText.length == 0 {
            guard let font = editor.attributedText.attribute(.font, at: editor.selectedRange.location - 1, effectiveRange: nil) as? UIFont else { return }
            editor.typingAttributes[.font] = font.toggled(trait: trait)
            return
        }
```

It only looks at the attributes for the letter before the selected range. If you previously set something to `editor.typingAttributes` without typing it will be reset.

The code in the previous if-statement does the correct thing for this case.

```
        if editor.isEmpty || editor.selectedRange == .zero {
            guard let font = editor.typingAttributes[.font] as? UIFont else { return }
            editor.typingAttributes[.font] = font.toggled(trait: trait)
            return
        }
```

**Comment by rajdeep** [comment]
thank you for reporting this issue, @YoX89. I should be able to get a fix out soon.

**Comment by rajdeep** [comment]
@YoX89, the check should indeed have been the same as in the previous statement. The bug has been fixed and merged. Thanks again.
