### ISSUE TITLE
Are there any plans to develop a complete set of Markdown text processing?

### ISSUE THREAD

**Issue by huanxsd** [rajdeep/proton#69]
Thank you for providing such a powerful and customizable library.
In the demo, there is a simple text processor demo: MakeupProcessing.
are there any plans to develop a complete set of Markdown text processing?
For example, support markdown bold, italic, quotation marks, lists, etc.

**Comment by rajdeep** [comment]
thank you for the appreciation, @huanxsd. As of now, I do not have any plans to incorporate other types of markdown processors. The example was created to demonstrate how it can be extended further. I am hoping that people who consume Proton would be able to create new processors/commands based on their requirements, and if they so wish, they may contribute back to Proton.

**Comment by huanxsd** [comment]
Got it, thank you very much
