### ISSUE TITLE
Placeholder doesn't appear after text deletion

### ISSUE THREAD

**Issue by vox-humana** [rajdeep/proton#72]
Before TextStorage replacement in  #66 `deleteBackward` caused `didCompleteLayout` layout manager delegate call which has `updatePlaceholderVisibility` inside.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/53595/97286476-a5757a00-1897-11eb-9593-38f80fbada42.png">

However, after this TextStorage update `didCompleteLayout` isn't being called anymore and after removing the last character placeholder doesn't appear.

Trying to figure out why it happens 🤔

**Comment by rajdeep** [comment]
Per my understanding, when the text is cleared, there's nothing really there to layout, and hence you don't get that event back. It seems that I should have had code to update visibility of the placeholder in `deleteBackwards` as well. This fix should work for you.

**Comment by vox-humana** [comment]
> when the text is cleared, there's nothing really there to layout

Well, that's true except that isn't what happens with swift TextStorage (see callstack image from old version). Which by itself opens the question what else has changed after we introduced PRTextStorage. 

Talking about the issue. 
`deleteBackward` works for the case when user presses delete button, however, it doesn't work when simple setAttributedString is called. 

I am looking for better place (closer to storage) where to place placeholder visibility check.

**Comment by rajdeep** [comment]
The difference could be there just because of Swift-ObjC mapping. I'll spend some more time looking into it as there could be other issues like you pointed out. However, the check needs to be in RichTextView and not storage. Placeholder is an attribute of textview, so that seems more apt to me. I'd been thinking about putting code in text changed. That might just be the right place.

**Comment by vox-humana** [comment]
Talking about storage I didn't mean `NSTextStorage` exactly, but was talking about attributed string. Unfortunately, `UITextViewDelegate` methods are not being called when we set `UITextView` content in code so need to find a better place for this check.

**Comment by vox-humana** [comment]
I have two possible fixes:
1. Add `didSet` on `RichTextView::attributedText` and `RichTextView::text` properties
2. Notify `RichTextView` from `PRTextStorage::edited:range:changeInLength` via `TextStorageDelegate` (this should work with any storage modification so we don't need two other checks)

What option do you prefer @rajdeep? I am leaning towards the second option

**Comment by rajdeep** [comment]
@vox-humana, second option looks good to me too.

**Comment by vox-humana** [comment]
Probably, easier to show in code. Raised a PR, looking for feedback ;)
