### ISSUE TITLE
Installing with SPM fails due to mixed language source files

### ISSUE THREAD

**Issue by torfluor** [rajdeep/proton#76]
When trying to include Proton in my project using SPM I get the following error message:
target at '[...]/SourcePackages/checkouts/proton/Proton/Sources' contains mixed language source files; feature not supported

I only get this issue on the master branch. Installing from the 0.5.0 tag works fine.

**Comment by rajdeep** [comment]
thanks for creating the issue, @torfluor. This has already been highlighted in issue #26, along with the same solution/workaround you have here. I have not been able to find time to look into this and if there are any possible solutions. I'll keep this open and will try to revisit in near future.

**Comment by vmanot** [comment]
@torfluor @rajdeep I fixed this in #82 - please take a look.

**Comment by rajdeep** [comment]
@torfluor, this has been fixed in the latest release 0.6.0.
