### ISSUE TITLE
Support for SwiftUI 

### ISSUE THREAD

**Issue by vmanot** [rajdeep/proton#83]
Proton currently doesn't offer any SwiftUI ready APIs.

**Comment by vmanot** [comment]
@rajdeep I'm willing to work on this, let me know if this is within the scope of the project or not.

**Comment by rajdeep** [comment]
that'd be great @vmanot. I have not been able to manage any time lately. While I do hope to be able to spend more time in near future, I don't think I will be able to get to this any time soon. You may look into this and we can have a discussion once you have an idea on how you plan to approach this.

**Comment by vmanot** [comment]
@rajdeep I understand - I think I'll develop it as a separate package then (I don't want to diverge too far from `master` and at the same time intend to use it across a few projects). If/when it reaches maturity, you could consider absorbing it back into the main framework if appropriate.

**Comment by rajdeep** [comment]
sounds like a plan! thanks again!

**Comment by papajyp** [comment]
I have been working on a basic swiftui Rich Text Editor. I am lacking lists. I might be able to help. I am interested at least incorporating what you have into my app.

**Comment by rajdeep** [comment]
that's cool, @papajyp. Please feel free to share any ideas, suggestions or code that you think would help get SwiftUI support.
