### ISSUE TITLE
List Items - bullets not displayed

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#88]
I'm trying to get lists working. The attributed text looks the same as that produced by the example app, but the bullets don't appear, so I guess I'm missing a step somewhere. I've tried setting the listItem value to a bullet character and also the string "listItemValue".

I've traced through the code but can't see what's going wrong, although I did come across a TODO that questions the code at line 141 of LayoutManager.

Here's the attributed text for three lines:

Line 1{
    NSColor = "<UIDynamicSystemColor: 0x60000318dc00; name = labelColor>";
    NSFont = "<UICTFont: 0x7ffb9e42c4f0> font-family: \"Helvetica\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 12/24, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0";
    "_listItem" = listItemValue;
}
{
    NSColor = "<UIDynamicSystemColor: 0x60000318dc00; name = labelColor>";
    NSFont = "<UICTFont: 0x7ffb9e42c4f0> font-family: \"Helvetica\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 12/24, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0";
    "_blockContentType" = "Proton.EditorContent.Name(rawValue: \"_newline\")";
    "_listItem" = listItemValue;
}Line 2{
    NSColor = "<UIDynamicSystemColor: 0x60000318dc00; name = labelColor>";
    NSFont = "<UICTFont: 0x7ffb9e42c4f0> font-family: \"Helvetica\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 12/24, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0";
    "_listItem" = listItemValue;
}
{
    NSColor = "<UIDynamicSystemColor: 0x60000318dc00; name = labelColor>";
    NSFont = "<UICTFont: 0x7ffb9e42c4f0> font-family: \"Helvetica\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 12/24, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0";
    "_blockContentType" = "Proton.EditorContent.Name(rawValue: \"_newline\")";
    "_listItem" = listItemValue;
}Line 3{
    NSColor = "<UIDynamicSystemColor: 0x60000318dc00; name = labelColor>";
    NSFont = "<UICTFont: 0x7ffb9e42c4f0> font-family: \"Helvetica\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
    NSParagraphStyle = "Alignment 0, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 12/24, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 0";
    "_listItem" = listItemValue;
}

Here's a screenshot:
<img width="545" alt="Screenshot 2021-01-07 at 13 09 07" src="https://user-images.githubusercontent.com/25199371/103896305-b0475900-50e9-11eb-88ea-35c305843012.png">

**Comment by rajdeep** [comment]
@writing-shed, can you please check if you are providing the  `editor.listFormattingProvider` correctly? As I see, in your sample, the `headIndent` of paragraphStyle is 0. This needs to be a value greater than 0 to add bullets. This is what controls how much a list item is indented. Note that `listLineFormatting` in `ListFormattingProvider` needs to have indentation value of greater than 0.

A correct sample should look something like this:
```swift
Line 1{
    NSColor = "<UIMacSystemColor: 0x6000000309f0; name = labelColor>";
    NSFont = "\".SFNS-Regular 17.00 pt. P [] (0x101e0cbc0) fobj=0x101e0cbc0, spc=4.67\"";
    NSParagraphStyle = "Alignment 4, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 25, TailIndent 0, FirstLineHeadIndent 25, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection 0, HyphenationFactor 0, TighteningForTruncation YES, HeaderLevel 0 LineBreakStrategy 0";
    "_listItem" = listItemValue;
}
```
Just to ensure that there's no issue with the ListFormattingProvider that you are using, you can try _not setting_ it in the editor. That will force use the inbuilt provider that just shows * instead of bullet item and uses default of 25 indentation point. You can also checkout a working example in `CommandsExampleViewController.swift`.

You may checkout the documentation [here](https://rajdeep.github.io/proton/Protocols/EditorListFormattingProvider.html).

**Comment by writing-shed** [comment]
Aha, I'd missed the ListFormattingProvider! After a few false starts I've managed to generate a List (see screenshot). In order to manage nested lists I will have to provide some UI furniture to generate tabs etc, these not being on an IOS screen keyboard. Thanks for your help.

<img width="545" alt="Screenshot 2021-01-09 at 14 41 25" src="https://user-images.githubusercontent.com/25199371/104094592-b83dff00-5289-11eb-9a4b-28c6e25d8fe9.png">

**Comment by rajdeep** [comment]
There's some bit of involved logic in creating lists. While you can certainly manage attributes yourself to make the list work, I would recommend trying out [ListCommand](https://rajdeep.github.io/proton/Classes/ListCommand.html) and [ListTextProcessor](https://rajdeep.github.io/proton/Classes/ListTextProcessor.html) if you are not already using it. ListCommand can be hooked on to the button that user taps to start a list with or without selecting text, and the ListTextProcessor will then take case of all the special keys like Enter, Tab, Shift-Tab etc.

**Comment by glennposadas** [comment]
Hi @rajdeep and @writing-shed . How do I replace the number list with actual bullets? OR say with a specific character? Thank you so much! And thanks @rajdeep really for creating this project.

**Comment by rajdeep** [comment]
@glennposadas, you can control the bullets/numbers using the [EditorListFormattingProvider. lineMarkerFor](https://rajdeep.github.io/proton/Protocols/EditorListFormattingProvider.html#/s:6Proton28EditorListFormattingProviderP17listLineMarkerFor6editor5index5level13previousLevel14attributeValueAA0cgH0OAA0B4ViewC_S3iypSgtF). Based on your logic, you can return [ListLineMarker](https://rajdeep.github.io/proton/Enums/ListLineMarker.html) that is either an image or a string. Using this, you can return any character that you wish to be used for the bullets. To see an example, checkout [ListFormattingProvider](https://github.com/rajdeep/proton/blob/master/ExampleApp/ExampleApp/AdvancedFeatures/CommandsExampleViewController.swift#L248) in Example App.
