### ISSUE TITLE
Storing & setting of contents in EditorView programatically

### ISSUE THREAD

**Issue by santi-g-s** [rajdeep/proton#89]
I am trying to store and set the data in EditorView to/from core data persistence. 

I came across `EditorView.contents()` to extract the array of `EditorContent` that I could store to CoreData. However I'm not quite sure how to set this data to the EditorView from the persistent store? Is this the best way to handle data storage from the EditorView? 

I don't just want to store the attributed string, but everything needed to recreate the layout of the editor view. 

Many thanks for the great work being done with proton, this is a great library and I'm looking forward to where it can go.

**Comment by writing-shed** [comment]
Nor sure what you mean by `recreate the layout of the editor `. I use `EditorView.attributedText` with embedded `NSParagraphStyle` attributes. (see issue #88 for screenshots).

**Comment by santi-g-s** [comment]
Oh of course. Didn't realise that all I needed was the attributedText. Just to clarify: the attributes include whether a string is a list item or not, correct? 

Best wishes and thank you for your help.

> Nor sure what you mean by `recreate the layout of the editor `. I use `EditorView.attributedText` with embedded `NSParagraphStyle` attributes. (see issue #88 for screenshots).

**Comment by writing-shed** [comment]
For lists you need to embed the paragraphs in the list within a single `.listItem` attribute. You also need to provide an `editor. listFormattingProvider` as per Rajdeep’s comment in issue #88.
