### ISSUE TITLE
Can't access EditorCommands in ProtonExtensions when using SPM

### ISSUE THREAD

**Issue by santi-g-s** [rajdeep/proton#90]
When using SPM to install proton 0.5.0, I cannot access BoldCommand(),  ItalicCommand(), etc or anything within the ProtonExtensions folder. 

To recreate issue:
```
import Foundation 
import Proton

let command = BoldCommand()
```

**Comment by rajdeep** [comment]
Thanks for reporting the issue. There's a PR open to fix SPM support. I hope to get this fixed with the same.

**Comment by rajdeep** [comment]
@santi-g-s, ProtonExtensions has been dropped and the commands are now available in Proton itself. Checkout the latest release.
