### ISSUE TITLE
EditorViewDelegate didChangeTextAt issue

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#91]
My app needs to respond to text changes in order to update its model data. I have implemented `func editor(_ editor: EditorView, didChangeTextAt range: NSRange)` to do this. If I enter some text, place the caret anywhere but the end, then enter a character, the character goes in the correct place but the caret is moved to the end. If I remove the delegate method it works OK (but obviously doesn't update the model). My delegate method does not invoke any Proton methods.

I have tried tracing through the code but can't pinpoint why this is happening, but it looks like it has to do with the way delegate methods are handled.

**Comment by rajdeep** [comment]
That's interesting. I'll check that out to see if I can recreate that behaviour. Can't think of why that might be happening 🤔 . Are you using any TextProcessors? If yes, can you try removing those and trying it again?

**Comment by writing-shed** [comment]
No, not using any TextProcessors. I'm going to try tracing through it again today. 

Best
Keith

**Comment by rajdeep** [comment]
@writing-shed,  I have verified this in the `CommandExampleViewController` and I do not see the behaviour that you have described. Also, within the scope of this delegate function, there's nothing that should really affect caret positioning. I recommend having a look at the Example App to see if you can spot what you might be missing in your code:

![text-delegate](https://user-images.githubusercontent.com/266423/104294834-cc952c80-5513-11eb-9596-4ac63544f079.gif)

**Comment by writing-shed** [comment]
Guess what? It was my fault. At some point after dealing with the text change I reset editor.attributedText which places the caret at the end. So I've saved the caret then reset it afterwards.

**Comment by rajdeep** [comment]
That's cool. So shall we close the issue?
