### ISSUE TITLE
enableSelectionHandles

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#95]
IMHO I think editor.enableSelectionHandles should default to false.

**Comment by rajdeep** [comment]
I think your suggestion makes sense. I'll look at that again and revise the code accordingly. Thank you for highlighting the possible improvement.

**Comment by writing-shed** [comment]
Excellent. As a matter of interest when might one need to set it true?

**Comment by rajdeep** [comment]
This is required to be `true` when you want to show the text as selected programatically. Checkout the `Scroll To` in Renderer example. Without this being `true`, the text that is found is not shown as selected and the Renderer does not scroll to that text.
