### ISSUE TITLE
EditorListFormattingProvider

### ISSUE THREAD

**Issue by writing-shed** [rajdeep/proton#97]
I have implemented my own `EditorListFormattingProvider`. Looking at your code it looks like I need to have a  `LayoutManagerDelegate` that overrides `listLineMarkerFor` somehow. Is that correct?

**Comment by rajdeep** [comment]
@writing-shed, the purpose of  `listLineMarkerFor` is to return the bullet/number that you wish to render to denote a list item. The argument passed in for levels are only to help consumers control the logic granularly. This acts as more like a standalone function that is eventually used by `LayoutManager` via `LayoutManagerDelegate`. However, `LayoutManagerDelegate` is internal and need not be accessed by consumers. Checkout [ListFormattingProvider](https://github.com/rajdeep/proton/blob/master/ExampleApp/ExampleApp/AdvancedFeatures/CommandsExampleViewController.swift#L249) in `CommandsExampleViewController` for example implementation.

**Comment by writing-shed** [comment]
Ok, I get that. So how can I configure Proton to use bullets other than those provided by the default ListFormatting provider (I have written my own SequenceGenerator).

**Comment by rajdeep** [comment]
Can you check if you have set `editor.listFormattingProvider` to your custom implementation? Once you do that, you can use your `SequenceGenerator` in the `EditorListFormattingProvider.listLineMarkerFor` that you have. Checkout `CommandsExampleViewController` for a sample implementation.

**Comment by writing-shed** [comment]
Thanks. No I hadn’t. I missed it on the editor API.

**Comment by writing-shed** [comment]
At first I fell foul of the weak reference in the editor, but it worked a treat once I realised.
